{% block page_head %}
    <script src="<?=$this->static("js/script_proj.js");?>"></script>
{% endblock %}

{% block nav_bar %}
<nav>
<a href="<?=$this->route("home")?>">Home</a>
<a href="<?=$this->route("projects")?>" >Projetos</a>
</nav>
{% endblock %}

<div id="box">
    <div id="box-content">
        <div class="content">
            <div id="left">
                <div class="hello">
                    <h1>Bem vindo a Página de Projetos</h1>
                </div>
                <div id="photo-div">
                    <img id="photo-project" class="circle" src="<?=$this->static("assets/images/background/proj_robot.png")?>" alt="robot-work">
                </div>
                <div id="text-proj">
                    <h2>Aqui você poderá encontrar meus projetos ou ideias.</h2>
                    <h2>Alguns ainda não foram iniciados, outros estão em andamento e outros pausados por problemas técnicos.</h2>
                    <h2>O projeto ficará disponivel para ser acessado assim que uma versão de teste ou superior for lançada.</h2>
                    <h2>Você também pode acompanhar o andamento de cada um deles em meu twitter ou instagram, ou até mesmo disponibilizo alguns em meu github.</h2>
                    <h2>Todas as medias podem ser acessadas na pagina home.</h2>
                </div>
            </div>
            <div id="right">
                <div class="hello">
                    <h1>Projetos</h1>
                </div>
                <div id="buttons">
                </div>
                <div id="project-info-container">
                </div>
            </div>
        </div>
    </div>
</div>