<header>
    <div class="header-container">
        <img src="<?=$this->static("assets/images/background/left_logo.png")?>" alt="left-logo">
        <img src="<?=$this->static("assets/images/background/central_logo.png")?>" alt="central-logo">
        <img src="<?=$this->static("assets/images/background/right_logo.png")?>" alt="right-logo">
    </div>
</header>
<nav>
<a href="<?=$this->route("index/home")?>">Home</a>
<a href="<?=$this->route("index/projects")?>" >Projetos</a>
<a href="">Contate-Me</a>
</nav>

